### ISSUE TITLE
SpinInput, when you hit enter after changing a value, it is not preserved on focus change.

### ISSUE THREAD

**Issue by Noemata** [YKSoftware/YKToolkit.Controls#1]
SpinInput:

When you hit enter after editing a value, the value reverts to its previous state after a focus change.

Also, did you intend to remove (not support) bindings that are set for the Text part of the control?  If that is the intention, that's ok.  Otherwise you should use the SetCurrentValue call in other parts of your code.

I have implemented a fix as shown below:

        private void InputTextBox_KeyDown(object sender, KeyEventArgs e)
        {
            var textbox = sender as TextBox;
            if (textbox == null)
                return;

            if (e.Key == Key.Enter)
            {
				// MP! was:
                //_newText = textbox.Text;

                UpdateValueFromText(textbox.Text, this.NumberStyle);

				// MP! added:
				textbox.SetCurrentValue(TextBox.TextProperty, textbox.Text);

                //var targetProperty = TextBox.TextProperty;
                //var bindingExpression = BindingOperations.GetBindingExpression(textbox, targetProperty);
                //if (bindingExpression != null)
                //{
                //    // データバインディングのソースを更新する
                //    bindingExpression.UpdateSource();
                //}
            }
        }

**Comment by YKSoftware** [comment]
Thank you for such advises.
Its bug fix will reflect in next version.
